{{- $GiB := 1073741824.0 -}}
{{- $used := printf "%.2f" (divf (add (.UserInfo.Download | default 0 | float64) (.UserInfo.Upload | default 0 | float64)) $GiB) -}}
{{- $traffic := (.UserInfo.Traffic | default 0 | float64) -}}
{{- $total := printf "%.2f" (divf $traffic $GiB) -}}

{{- $exp := "" -}}
{{- $expStr := printf "%v" .UserInfo.ExpiredAt -}}
{{- if regexMatch `^[0-9]+$` $expStr -}}
  {{- $ts := $expStr | float64 -}}
  {{- $sec := ternary (divf $ts 1000.0) $ts (ge (len $expStr) 13) -}}
  {{- $exp = (date "2006-01-02 15:04:05" (unixEpoch ($sec | int64))) -}}
{{- else -}}
  {{- $exp = $expStr -}}
{{- end -}}

{{- $supportedProxies := list -}}
{{- range $proxy := .Proxies -}}
  {{- if or (eq $proxy.Type "shadowsocks") (eq $proxy.Type "vmess") (eq $proxy.Type "trojan") (eq $proxy.Type "anytls") (eq $proxy.Type "http") (eq $proxy.Type "https") (eq $proxy.Type "socks5") (eq $proxy.Type "socks5-tls") -}}
    {{- $supportedProxies = append $supportedProxies $proxy -}}
  {{- end -}}
{{- end -}}


# -------------------------------------------------------
# Quantumult X Profile (Generated by Go Template)
# Site: {{ .SiteName | default "Service" }}
# Subscribe: {{ .SubscribeName | default "Default" }}
# Traffic: {{ $used }} GiB/{{ $total }} GiB | Expires: {{ $exp }}
# Generated at: {{ now | date "2006-01-02 15:04:05" }}
# -------------------------------------------------------

{{- range $proxy := $supportedProxies }}
  {{- $server := $proxy.Server -}}
  {{- if and (contains $proxy.Server ":") (not (hasPrefix "[" $proxy.Server)) -}}
    {{- $server = printf "[%s]" $proxy.Server -}}
  {{- end -}}

  {{- $sni := default "" $proxy.SNI -}}
  {{- if eq $sni "" -}}
    {{- $sni = default "" $proxy.Host -}}
  {{- end -}}
  {{- if and (eq $sni "") (not (or (regexMatch "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$" $proxy.Server) (contains $proxy.Server ":"))) -}}
    {{- $sni = $proxy.Server -}}
  {{- end -}}

  {{- $password := $.UserInfo.Password -}}
  {{- if and (eq $proxy.Type "shadowsocks") (ne (default "" $proxy.ServerKey) "") -}}
    {{- $method := $proxy.Method -}}
    {{- if or (hasPrefix "2022-blake3-" $method) (eq $method "2022-blake3-aes-128-gcm") (eq $method "2022-blake3-aes-256-gcm") -}}
      {{- $userKeyLen := ternary 16 32 (hasSuffix "128-gcm" $method) -}}
      {{- $pwdStr := printf "%s" $password -}}
      {{- $userKey := ternary $pwdStr (trunc $userKeyLen $pwdStr) (le (len $pwdStr) $userKeyLen) -}}
      {{- $serverB64 := b64enc $proxy.ServerKey -}}
      {{- $userB64 := b64enc $userKey -}}
      {{- $password = printf "%s:%s" $serverB64 $userB64 -}}
    {{- end -}}
  {{- end -}}

  {{- $common := "fast-open=false, udp-relay=true" -}}

  {{- if eq $proxy.Type "shadowsocks" }}
    {{- $method := default "aes-128-gcm" $proxy.Method }}
shadowsocks={{ $server }}:{{ $proxy.Port }}, method={{ $method }}, password={{ $password }}{{- if eq $proxy.Transport "http" }}, obfs=http{{- if ne (default "" $proxy.Host) "" }}, obfs-host={{ $proxy.Host }}{{- end }}{{- if ne (default "" $proxy.Path) "" }}, obfs-uri={{ $proxy.Path }}{{- end }}{{- else if eq $proxy.Transport "tls" }}, obfs=tls{{- else if or (eq $proxy.Transport "ws") (eq $proxy.Transport "websocket") }}, obfs=ws{{- if ne (default "" $proxy.Path) "" }}, obfs-uri={{ $proxy.Path }}{{- end }}{{- else if eq $proxy.Transport "wss" }}, obfs=wss{{- if ne (default "" $proxy.Path) "" }}, obfs-uri={{ $proxy.Path }}{{- end }}{{- end }}, {{ $common }}, tag={{ $proxy.Name }}
  {{- else if eq $proxy.Type "vmess" }}
vmess={{ $server }}:{{ $proxy.Port }}, method=none, password={{ $password }}{{- if or (eq (default "" $proxy.Security) "tls") (eq $proxy.Transport "over-tls") }}, obfs=over-tls{{- end }}{{- if or (eq $proxy.Transport "ws") (eq $proxy.Transport "websocket") }}, obfs=ws{{- if ne (default "" $proxy.Path) "" }}, obfs-uri={{ $proxy.Path }}{{- end }}{{- end }}{{- if eq $proxy.Transport "wss" }}, obfs=wss{{- if ne (default "" $proxy.Path) "" }}, obfs-uri={{ $proxy.Path }}{{- end }}{{- end }}{{- if ne $sni "" }}, obfs-host={{ $sni }}{{- end }}, udp-relay=false, tag={{ $proxy.Name }}
  {{- else if eq $proxy.Type "trojan" }}
trojan={{ $server }}:{{ $proxy.Port }}, password={{ $password }}, over-tls=true{{- if ne $sni "" }}, tls-host={{ $sni }}{{- end }}{{- if $proxy.AllowInsecure }}, tls-verification=false{{- else }}, tls-verification=true{{- end }}, udp-relay=false, tag={{ $proxy.Name }}
  {{- else if eq $proxy.Type "anytls" }}
anytls={{ $server }}:{{ $proxy.Port }}, password={{ $password }}{{- if ne $sni "" }}, tls-host={{ $sni }}{{- end }}{{- if $proxy.AllowInsecure }}, tls-verification=false{{- else }}, tls-verification=true{{- end }}, udp-relay=false, tag={{ $proxy.Name }}
  {{- else if or (eq $proxy.Type "http") (eq $proxy.Type "https") }}
http={{ $server }}:{{ $proxy.Port }}{{- if or (ne (default "" $proxy.Username) "") (ne $password "") }}, username={{ default $password $proxy.Username }}, password={{ $password }}{{- end }}{{- if eq $proxy.Type "https" }}, over-tls=true{{- if ne $sni "" }}, tls-host={{ $sni }}{{- end }}{{- if $proxy.AllowInsecure }}, tls-verification=false{{- else }}, tls-verification=true{{- end }}{{- end }}, udp-relay=false, tag={{ $proxy.Name }}
  {{- else if or (eq $proxy.Type "socks5") (eq $proxy.Type "socks5-tls") }}
socks5={{ $server }}:{{ $proxy.Port }}{{- if or (ne (default "" $proxy.Username) "") (ne $password "") }}, username={{ default $password $proxy.Username }}, password={{ $password }}{{- end }}{{- if eq $proxy.Type "socks5-tls" }}, over-tls=true{{- if ne $sni "" }}, tls-host={{ $sni }}{{- end }}{{- if $proxy.AllowInsecure }}, tls-verification=false{{- else }}, tls-verification=true{{- end }}{{- end }}, udp-relay=false, tag={{ $proxy.Name }}
  {{- end }}
{{- end }}

{{- range $proxy := .Proxies }}
  {{- if not (or (eq $proxy.Type "shadowsocks") (eq $proxy.Type "vmess") (eq $proxy.Type "trojan") (eq $proxy.Type "anytls") (eq $proxy.Type "http") (eq $proxy.Type "https") (eq $proxy.Type "socks5") (eq $proxy.Type "socks5-tls")) }}
# Skipped (unsupported by Quantumult X): {{ $proxy.Name }} ({{ $proxy.Type }})
  {{- end }}
{{- end }}
